config/routes.rb
Rails.application.routes.draw do

  get 'devolucion_compras/get_compras' => 'devolucion_compras#get_compras'
  get 'devolucion_compras/buscar_compra' => 'devolucion_compras#buscar_compra'
  get 'devolucion_compras/imprimir' => 'devolucion_compras#imprimir'
  get 'devolucion_compras/:id/imprimir_show' => 'devolucion_compras#imprimir_show'
  resources :devolucion_compras

  get 'devolucion_ventas/get_ventas' => 'devolucion_ventas#get_ventas'
  get 'devolucion_ventas/buscar_venta' => 'devolucion_ventas#buscar_venta'
  get 'devolucion_ventas/imprimir' => 'devolucion_ventas#imprimir'
  get 'devolucion_ventas/:id/imprimir_show' => 'devolucion_ventas#imprimir_show'
  resources :devolucion_ventas

  devise_for :users

  get 'configuraciones/check_empresa_nombre' => 'configuraciones#check_empresa_nombre'
  resources :configuraciones, only: [:index, :edit, :update]

  get 'proveedores/check_nombre' => 'proveedores#check_nombre'
  get 'proveedores/buscar' => 'proveedores#buscar'
  resources :proveedores

  get 'clientes/check_nombre' => 'clientes#check_nombre'
  get 'clientes/buscar' => 'clientes#buscar'
  resources :clientes

  get 'cuentas_corrientes/clientes'
  get 'cuentas_corrientes/proveedores'
  get 'cuentas_corrientes/imprimir_extracto'

  get 'empleados/check_nombre' => 'empleados#check_nombre'
  resources :empleados

  get 'categorias/check_nombre' => 'categorias#check_nombre'
  resources :categorias

  get 'mercaderias/check_codigo' => 'mercaderias#check_codigo'
  get 'mercaderias/buscar' => 'mercaderias#buscar'
  get 'mercaderias/historico' => 'mercaderias#historico'
  get 'mercaderias/imprimir_historico' => 'mercaderias#imprimir_historico'
  resources :mercaderias, except: [:show]

  resources :inventarios, only: [:index]

  resources :movimiento_mercaderias

  get 'monedas/check_nombre' => 'monedas#check_nombre'
  resources :monedas

  get 'categoria_gastos/check_nombre' => 'categoria_gastos#check_nombre'
  resources :categoria_gastos

  get 'compras/buscar_devoluciones' => 'compras#buscar_devoluciones'
  get 'compras/imprimir' => 'compras#imprimir'
  get 'compras/:id/imprimir_show' => 'compras#imprimir_show'
  resources :compras

  get 'ventas/buscar_devoluciones' => 'ventas#buscar_devoluciones'
  get 'ventas/imprimir' => 'ventas#imprimir'
  get 'ventas/:id/imprimir_show' => 'ventas#imprimir_show'
  resources :ventas

  get 'pagos/buscar_pendientes' => 'pagos#buscar_pendientes'
  get 'pagos/imprimir' => 'pagos#imprimir'
  get 'pagos/:id/imprimir_show' => 'pagos#imprimir_show'
  resources :pagos

  get 'caja_movimientos/new_transferencia' => 'caja_movimientos#new_transferencia'
  post 'caja_movimientos/create_transferencia' => 'caja_movimientos#create_transferencia'
  get 'caja_movimientos/imprimir' => 'caja_movimientos#imprimir'
  get 'caja_movimientos/:id/imprimir_show' => 'caja_movimientos#imprimir_show'

  resources :caja_movimientos, except: [:edit, :update, :destroy]

  get 'cobros/buscar_pendientes' => 'cobros#buscar_pendientes'
  get 'cobros/imprimir' => 'cobros#imprimir'
  get 'cobros/:id/imprimir_show' => 'cobros#imprimir_show'
  resources :cobros

  get 'reportes/compras'
  get 'reportes/imprimir_reporte_compras'
  get 'reportes/ventas'
  get 'reportes/imprimir_reporte_ventas'
  get 'reportes/gastos'
  get 'reportes/imprimir_reporte_gastos'
  get 'reportes/caja'
  get 'reportes/imprimir_reporte_caja'

  get 'welcome/index'
  get 'welcome/devoluciones_venta'
  get 'welcome/devoluciones_compra'
  get 'welcome/devoluciones_venta_index'
  get 'welcome/devoluciones_compra_index'

  root 'welcome#index'

end

app/models/cliente.rb
class Cliente < Persona
  has_many :ventas, foreign_key: 'persona_id'
  has_many :ventas_pendientes, -> { where(estado: :pendiente) }, class_name: 'Venta', foreign_key: 'persona_id'

  has_many :devoluciones_disponibles, -> { where.not(credito_restante: 0) }, class_name: 'NotasCreditosDebito', foreign_key: 'persona_id'

  validates :nombre, presence: true, length: {maximum: 150, minimum: 2}, uniqueness: true
  validates :numero_documento, format: { with: /\d+-?\d+\z/, message: :only_numbers_is_allowed }
  before_destroy :tiene_deuda?

  def tiene_deuda?
    if saldo_actual == 0
      true
    else
        errors.add(:base, "El cliente tiene operaciones pendientes")
        false
    end
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  before_action :setup_menu, only: [:index]

  # configuracion del menu
  def setup_menu
    @menu_setup[:main_menu] = :ventas
    @menu_setup[:side_menu] = :clientes_sidemenu
  end

  # buscador de proveedores
  def buscar
    get_clientes
    render json: {items: @clientes, total_count: @clientes.total_count}
  end

  # GET /clientes
  # GET /clientes.json
  def index
    get_clientes
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    render 'load_form', format: :js
  end

  # GET /clientes/1/edit
  def edit
    render 'load_form', format: :js
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      @error = false
      @message = "Se ha guardado el cliente"
      get_clientes
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de guardar el cliente. #{@cliente.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update

    if @cliente.update(cliente_params)
      @error = false
      @message = "Se ha guardado el cliente"
      get_clientes
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de guardar el cliente. #{@cliente.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js

  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    if @cliente.destroy
      @error = false
      @message = "Se ha eliminado el cliente"
      get_clientes
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de eliminar el cliente. #{@cliente.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js
  end

  # Comprobar si ya existe el proveedor con el nombre dado
  def check_nombre
    cliente = Cliente.by_nombre(params[:nombre]).first

    render json: (cliente.nil? || cliente.id == params[:id].to_i) ? true : t('cliente.unique_nombre_error', nombre: params[:nombre]).to_json
  end

  def get_clientes
    @search = Cliente.search(params[:q])
    @clientes = @search.result.page(params[:page])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :telefono, :direccion, :numero_documento, :limite_credito)
    end
end

app/views/clientes/_form.html.slim
= simple_form_for cliente, url: !cliente.new_record? ? cliente_path(cliente) : clientes_path,
                              html: {id: 'cliente-form'},
                              remote: true do |f|
  .modal-header
    button.close type="button" data-dismiss="modal"
      span &times;
    h4.modal-title
      = cliente.new_record? ? 'Nuevo cliente' : 'Editar cliente'
  .modal-body
    - if params[:from_boletas].present?
      = hidden_field_tag :from_boletas, value: true
    = f.input :id, as: :hidden, input_html: { id: 'cliente_id' }
    = f.input :nombre, autofocus: true, input_html: {class: 'uniqueClienteNombre'}
    = f.input :direccion
    = f.input :telefono
    = f.input :numero_documento
    = f.input :limite_credito, as: :string, input_html: {class: 'limiteNumero maskMoneda'}
  .modal-footer.text-right
    button.btn.btn-default.pull-left [type="button" data-dismiss="modal" aria-hidden="true"] Cancelar
    input.btn.btn-primary type="submit" value="Guardar" data-disable-with="Guardando..."

javascript:
  ClientesUI.initFormEvents("#{clientes_check_nombre_path}");

app/views/clientes/_list.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Nombre
      th RUC/CI
      th Dirección
      th Teléfono
      th Límite de crédito
      th
      th.table-actions
  tbody
    - clientes.each do |cliente|
      tr
        td = cortar_texto(cliente.nombre)
        td = cliente.numero_documento
        td = cortar_texto(cliente.direccion)
        td = cliente.telefono
        td = number_to_currency(cliente.limite_credito)
        td = link_to 'Movimientos', cuentas_corrientes_clientes_path(persona_id: cliente.id), class: 'btn btn-default btn-sm'
        td
          = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_cliente_path(cliente), remote: true, class: 'btn btn-default btn-sm'
          | #{' '}
          = link_to ' <i class="fa fa-trash"></i>'.html_safe, cliente_path(cliente), method: 'delete', data: {confirm: "¿Desea eliminar el cliente #{cliente.nombre}?"}, remote: true, class: 'btn btn-danger btn-sm'

app/views/clientes/index.html.slim
section.content-header
  h1 Ventas
section.content
  .row
    .col-xs-12
      .box
        .box-header
          h3.box-title Listado de Clientes
          .box-tools.pull-right
            = link_to 'Nuevo cliente', new_cliente_path, class: 'btn btn-primary', remote:true
        .box-body#clientes-lista
          #cliente-search.buscador-listado
            = search_form_for @search, remote:true, class: 'remote-search' do |f|
              .input-group
                = f.text_field :nombre_or_numero_documento_cont, class: 'form-control', placeholder: 'Buscar por nombre o RUC/CI...', autofocus: true
                .input-group-btn
                  button.btn.btn-default type="submit" name="commit"
                    i.fa.fa-search
          #clientes-table.overlay-wrapper.buscador-resultados.table-responsive
            = render partial: 'clientes/list', locals: {clientes: @clientes}
          #paginate-container
            = paginate @clientes, remote: true

app/views/clientes/index.js.slim
| $("#clientes-table").html("#{escape_javascript(render partial: 'list', format: 'html', locals: {clientes: @clientes})}");
| $('#paginate-container').html("#{escape_javascript(paginate(@clientes, remote: true)) }");
| $('.buscador-resultados > .overlay').remove();

app/views/clientes/load_form.js.slim
| var modal = $('#main-modal');
| modal.find('.modal-content').html("#{escape_javascript(render partial: 'form', format: :html, locals: {cliente: @cliente})}");
| modal.modal('show');

app/views/clientes/reload_list.js.slim
| var modal = $('#main-modal');
- if @error
  | noty({type: "error", text : "#{@message}"});
- else
  | noty({type: "success", text : "#{@message}"});
  | modal.modal('hide');
  - if params[:from_boletas].present?
    | $("#limite_credito").html(NumberHelper.aMoneda(#{@cliente.limite_credito}));
    | $("#saldo").html(NumberHelper.aMoneda(#{@cliente.limite_credito - @cliente.saldo_actual}));
    | $("#personas-buscador").select2('data', #{@cliente.to_json.html_safe})
  - else
    | $('#clientes-table').html("#{escape_javascript(render 'list', clientes: @clientes)}");
    | $('#paginate-container').html("#{escape_javascript(paginate(@clientes, params: {controller: :clientes, action: :index}, remote: true)) }");

app/views/clientes/show.html.slim
p#notice = notice


= link_to 'Edit', edit_clientes_path(@clientes)
'|
= link_to 'Back', clientes_path