config/routes.rb
Rails.application.routes.draw do

  get 'devolucion_compras/get_compras' => 'devolucion_compras#get_compras'
  get 'devolucion_compras/buscar_compra' => 'devolucion_compras#buscar_compra'
  get 'devolucion_compras/imprimir' => 'devolucion_compras#imprimir'
  get 'devolucion_compras/:id/imprimir_show' => 'devolucion_compras#imprimir_show'
  resources :devolucion_compras

  get 'devolucion_ventas/get_ventas' => 'devolucion_ventas#get_ventas'
  get 'devolucion_ventas/buscar_venta' => 'devolucion_ventas#buscar_venta'
  get 'devolucion_ventas/imprimir' => 'devolucion_ventas#imprimir'
  get 'devolucion_ventas/:id/imprimir_show' => 'devolucion_ventas#imprimir_show'
  resources :devolucion_ventas

  devise_for :users

  get 'configuraciones/check_empresa_nombre' => 'configuraciones#check_empresa_nombre'
  resources :configuraciones, only: [:index, :edit, :update]

  get 'proveedores/check_nombre' => 'proveedores#check_nombre'
  get 'proveedores/buscar' => 'proveedores#buscar'
  resources :proveedores

  get 'clientes/check_nombre' => 'clientes#check_nombre'
  get 'clientes/buscar' => 'clientes#buscar'
  resources :clientes

  get 'cuentas_corrientes/clientes'
  get 'cuentas_corrientes/proveedores'
  get 'cuentas_corrientes/imprimir_extracto'

  get 'empleados/check_nombre' => 'empleados#check_nombre'
  resources :empleados

  get 'categorias/check_nombre' => 'categorias#check_nombre'
  resources :categorias

  get 'mercaderias/check_codigo' => 'mercaderias#check_codigo'
  get 'mercaderias/buscar' => 'mercaderias#buscar'
  get 'mercaderias/historico' => 'mercaderias#historico'
  get 'mercaderias/imprimir_historico' => 'mercaderias#imprimir_historico'
  resources :mercaderias, except: [:show]

  resources :inventarios, only: [:index]

  resources :movimiento_mercaderias

  get 'monedas/check_nombre' => 'monedas#check_nombre'
  resources :monedas

  get 'categoria_gastos/check_nombre' => 'categoria_gastos#check_nombre'
  resources :categoria_gastos

  get 'compras/buscar_devoluciones' => 'compras#buscar_devoluciones'
  get 'compras/imprimir' => 'compras#imprimir'
  get 'compras/:id/imprimir_show' => 'compras#imprimir_show'
  resources :compras

  get 'ventas/buscar_devoluciones' => 'ventas#buscar_devoluciones'
  get 'ventas/imprimir' => 'ventas#imprimir'
  get 'ventas/:id/imprimir_show' => 'ventas#imprimir_show'
  resources :ventas

  get 'pagos/buscar_pendientes' => 'pagos#buscar_pendientes'
  get 'pagos/imprimir' => 'pagos#imprimir'
  get 'pagos/:id/imprimir_show' => 'pagos#imprimir_show'
  resources :pagos

  get 'caja_movimientos/new_transferencia' => 'caja_movimientos#new_transferencia'
  post 'caja_movimientos/create_transferencia' => 'caja_movimientos#create_transferencia'
  get 'caja_movimientos/imprimir' => 'caja_movimientos#imprimir'
  get 'caja_movimientos/:id/imprimir_show' => 'caja_movimientos#imprimir_show'

  resources :caja_movimientos, except: [:edit, :update, :destroy]

  get 'cobros/buscar_pendientes' => 'cobros#buscar_pendientes'
  get 'cobros/imprimir' => 'cobros#imprimir'
  get 'cobros/:id/imprimir_show' => 'cobros#imprimir_show'
  resources :cobros

  get 'reportes/compras'
  get 'reportes/imprimir_reporte_compras'
  get 'reportes/ventas'
  get 'reportes/imprimir_reporte_ventas'
  get 'reportes/gastos'
  get 'reportes/imprimir_reporte_gastos'
  get 'reportes/caja'
  get 'reportes/imprimir_reporte_caja'

  get 'welcome/index'
  get 'welcome/devoluciones_venta'
  get 'welcome/devoluciones_compra'
  get 'welcome/devoluciones_venta_index'
  get 'welcome/devoluciones_compra_index'

  root 'welcome#index'

end

app/controllers/proveedores_controller.rb
class ProveedoresController < ApplicationController
  before_action :set_proveedor, only: [:show, :edit, :update, :destroy]
  before_action :setup_menu, only: [:index]

  # configuracion del menu
  def setup_menu
    @menu_setup[:main_menu] = :compras
    @menu_setup[:side_menu] = :proveedores_sidemenu
  end

  # buscador de proveedores
  def buscar
    get_proveedores
    render json: {items: @proveedores, total_count: @proveedores.total_count}
  end

  # GET /proveedores
  # GET /proveedores.json
  def index
    get_proveedores
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedor = Proveedor.new
    render 'load_form', format: :js
  end

  # GET /proveedores/1/edit
  def edit
    render 'load_form', format: :js
  end

  # POST /proveedores
  # POST /proveedores.json
  def create
    @proveedor = Proveedor.new(proveedor_params)

    if @proveedor.save
      @error = false
      @message = "Se ha guardado el proveedor"
      get_proveedores
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de guardar el proveedor. #{@proveedor.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js
  end

  # PATCH/PUT /proveedores/1
  # PATCH/PUT /proveedores/1.json
  def update

    if @proveedor.update(proveedor_params)
      @error = false
      @message = "Se ha guardado el proveedor"
      get_proveedores
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de guardar el proveedor. #{@proveedor.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js

  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    if @proveedor.destroy
      @error = false
      @message = "Se ha eliminado el proveedor"
      get_proveedores
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de eliminar el proveedor. #{@proveedor.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js
  end

  # Comprobar si ya existe el proveedor con el nombre dado
  def check_nombre
    proveedor = Proveedor.by_nombre(params[:nombre]).first

    render json: (proveedor.nil? || proveedor.id == params[:id].to_i) ? true : t('proveedor.unique_nombre_error', nombre: params[:nombre]).to_json
  end

  def get_proveedores
    @search = Proveedor.search(params[:q])
    @proveedores = @search.result.page(params[:page])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedor
      @proveedor = Proveedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedor_params
      procesar_monto
      params.require(:proveedor).permit(:id, :nombre, :direccion, :numero_documento, :telefono, :limite_credito)
    end

    def procesar_monto
      params[:proveedor][:limite_credito] = cantidad_a_numero(params[:proveedor][:limite_credito])
    end
end

app/views/proveedores/_form.html.slim
= simple_form_for proveedor, url: !proveedor.new_record? ? proveedor_path(proveedor) : proveedores_path,
                              html: {id: 'proveedor-form'},
                              remote: true do |f|
  .modal-header
    button.close type="button" data-dismiss="modal"
      span &times;
    h4.modal-title
      = proveedor.new_record? ? 'Nuevo proveedor' : 'Editar proveedor'
  .modal-body
    - if params[:from_boletas].present?
      = hidden_field_tag :from_boletas, value: true
    = f.input :id, as: :hidden, input_html: { id: 'proveedor_id' }
    = f.input :nombre, autofocus: true, input_html: {class: 'uniqueProveedorNombre'}
    = f.input :direccion
    = f.input :telefono
    = f.input :numero_documento
    = f.input :limite_credito, as: :string, input_html: {class: 'limiteNumero maskMoneda'}
  .modal-footer.text-right
    button.btn.btn-default.pull-left [type="button" data-dismiss="modal" aria-hidden="true"] Cancelar
    input.btn.btn-primary type="submit" value="Guardar" data-disable-with="Guardando..."

javascript:
  ProveedoresUI.initFormEvents("#{proveedores_check_nombre_path}");

app/views/proveedores/_list.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Nombre
      th RUC/CI
      th Dirección
      th Teléfono
      th Límite de crédito
      th
      th.table-actions
  tbody
    - proveedores.each do |proveedor|
      tr
        td = cortar_texto(proveedor.nombre)
        td = proveedor.numero_documento
        td = cortar_texto(proveedor.direccion)
        td = proveedor.telefono
        td = number_to_currency(proveedor.limite_credito)
        td = link_to 'Movimientos', cuentas_corrientes_proveedores_path(persona_id: proveedor.id), class: 'btn btn-default btn-sm'
        td
          = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_proveedor_path(proveedor), remote: true, class: 'btn btn-default btn-sm'
          | #{' '}
          = link_to ' <i class="fa fa-trash"></i>'.html_safe, proveedor_path(proveedor), method: 'delete', data: {confirm: "¿Desea eliminar el proveedor #{proveedor.nombre}?"}, remote: true, class: 'btn btn-danger btn-sm'

app/views/proveedores/index.html.slim
section.content-header
  h1 Compras
section.content
  .row
    .col-xs-12
      .box
        .box-header
          h3.box-title Listado de Proveedores
          .box-tools.pull-right
            = link_to 'Nuevo proveedor', new_proveedor_path, class: 'btn btn-primary', remote: true
        .box-body#proveedores-lista
          #proveedor-search.buscador-listado
            = search_form_for @search, remote: true, class: 'remote-search' do |f|
              .input-group
                = f.text_field :nombre_or_numero_documento_cont, class: 'form-control', placeholder: 'Buscar por nombre o RUC/CI...', autofocus: true
                .input-group-btn
                  button.btn.btn-default type="submit" name="commit"
                    i.fa.fa-search
          #proveedores-table.overlay-wrapper.buscador-resultados.table-responsive
            = render partial: 'proveedores/list', locals: {proveedores: @proveedores}
          #paginate-container
            = paginate @proveedores, remote: true

app/views/proveedores/index.js.slim
| $("#proveedores-table").html("#{escape_javascript(render partial: 'list', format: 'html', locals: {proveedores: @proveedores})}");
| $('#paginate-container').html("#{escape_javascript(paginate(@proveedores, remote: true)) }");
| $('.buscador-resultados > .overlay').remove();

app/views/proveedores/load_form.js.slim
| var modal = $('#main-modal');
| modal.find('.modal-content').html("#{escape_javascript(render partial: 'form', format: :html, locals: {proveedor: @proveedor})}");
| modal.modal('show');

app/views/proveedores/reload_list.js.slim
| var modal = $('#main-modal');
- if @error
  | noty({type: "error", text : "#{@message}"});
- else
  | noty({type: "success", text : "#{@message}"});
  | modal.modal('hide');
  - if params[:from_boletas].present?
    | $("#limite_credito").html(NumberHelper.aMoneda(#{@proveedor.limite_credito}));
    | $("#saldo").html(NumberHelper.aMoneda(#{@proveedor.limite_credito - @proveedor.saldo_actual}));
    | $("#personas-buscador").select2('data', #{@proveedor.to_json.html_safe})
  - else
    | $('#proveedores-table').html("#{escape_javascript(render 'list', proveedores: @proveedores)}");
    | $('#paginate-container').html("#{escape_javascript(paginate(@proveedores, params: {controller: :proveedores, action: :index}, remote: true)) }");

app/views/proveedores/show.html.slim
p#notice = notice


= link_to 'Edit', edit_proveedore_path(@proveedore)
'|
= link_to 'Back', proveedores_path