config/routes.rb
Rails.application.routes.draw do

  get 'devolucion_compras/get_compras' => 'devolucion_compras#get_compras'
  get 'devolucion_compras/buscar_compra' => 'devolucion_compras#buscar_compra'
  get 'devolucion_compras/imprimir' => 'devolucion_compras#imprimir'
  get 'devolucion_compras/:id/imprimir_show' => 'devolucion_compras#imprimir_show'
  resources :devolucion_compras

  get 'devolucion_ventas/get_ventas' => 'devolucion_ventas#get_ventas'
  get 'devolucion_ventas/buscar_venta' => 'devolucion_ventas#buscar_venta'
  get 'devolucion_ventas/imprimir' => 'devolucion_ventas#imprimir'
  get 'devolucion_ventas/:id/imprimir_show' => 'devolucion_ventas#imprimir_show'
  resources :devolucion_ventas

  devise_for :users

  get 'configuraciones/check_empresa_nombre' => 'configuraciones#check_empresa_nombre'
  resources :configuraciones, only: [:index, :edit, :update]

  get 'proveedores/check_nombre' => 'proveedores#check_nombre'
  get 'proveedores/buscar' => 'proveedores#buscar'
  resources :proveedores

  get 'clientes/check_nombre' => 'clientes#check_nombre'
  get 'clientes/buscar' => 'clientes#buscar'
  resources :clientes

  get 'cuentas_corrientes/clientes'
  get 'cuentas_corrientes/proveedores'
  get 'cuentas_corrientes/imprimir_extracto'

  get 'empleados/check_nombre' => 'empleados#check_nombre'
  resources :empleados

  get 'categorias/check_nombre' => 'categorias#check_nombre'
  resources :categorias

  get 'mercaderias/check_codigo' => 'mercaderias#check_codigo'
  get 'mercaderias/buscar' => 'mercaderias#buscar'
  get 'mercaderias/historico' => 'mercaderias#historico'
  get 'mercaderias/imprimir_historico' => 'mercaderias#imprimir_historico'
  resources :mercaderias, except: [:show]

  resources :inventarios, only: [:index]

  resources :movimiento_mercaderias

  get 'monedas/check_nombre' => 'monedas#check_nombre'
  resources :monedas

  get 'categoria_gastos/check_nombre' => 'categoria_gastos#check_nombre'
  resources :categoria_gastos

  get 'compras/buscar_devoluciones' => 'compras#buscar_devoluciones'
  get 'compras/imprimir' => 'compras#imprimir'
  get 'compras/:id/imprimir_show' => 'compras#imprimir_show'
  resources :compras

  get 'ventas/buscar_devoluciones' => 'ventas#buscar_devoluciones'
  get 'ventas/imprimir' => 'ventas#imprimir'
  get 'ventas/:id/imprimir_show' => 'ventas#imprimir_show'
  resources :ventas

  get 'pagos/buscar_pendientes' => 'pagos#buscar_pendientes'
  get 'pagos/imprimir' => 'pagos#imprimir'
  get 'pagos/:id/imprimir_show' => 'pagos#imprimir_show'
  resources :pagos

  get 'caja_movimientos/new_transferencia' => 'caja_movimientos#new_transferencia'
  post 'caja_movimientos/create_transferencia' => 'caja_movimientos#create_transferencia'
  get 'caja_movimientos/imprimir' => 'caja_movimientos#imprimir'
  get 'caja_movimientos/:id/imprimir_show' => 'caja_movimientos#imprimir_show'

  resources :caja_movimientos, except: [:edit, :update, :destroy]

  get 'cobros/buscar_pendientes' => 'cobros#buscar_pendientes'
  get 'cobros/imprimir' => 'cobros#imprimir'
  get 'cobros/:id/imprimir_show' => 'cobros#imprimir_show'
  resources :cobros

  get 'reportes/compras'
  get 'reportes/imprimir_reporte_compras'
  get 'reportes/ventas'
  get 'reportes/imprimir_reporte_ventas'
  get 'reportes/gastos'
  get 'reportes/imprimir_reporte_gastos'
  get 'reportes/caja'
  get 'reportes/imprimir_reporte_caja'

  get 'welcome/index'
  get 'welcome/devoluciones_venta'
  get 'welcome/devoluciones_compra'
  get 'welcome/devoluciones_venta_index'
  get 'welcome/devoluciones_compra_index'

  root 'welcome#index'

end

app/models/cobro.rb
class Cobro < Recibo

  belongs_to :persona, -> { with_deleted }, foreign_key: "persona_id", inverse_of: :boletas, class_name: 'Cliente'

  has_many :boletas_detalles, class_name: 'CobroVenta', dependent: :destroy, foreign_key: "recibo_id", inverse_of: :recibo
  has_many :boletas, class_name: 'Venta', through: :boletas_detalles

  delegate :nombre, to: :persona, prefix: true

  def build_detalles(monedas_usadas = [])
    Moneda.all.each do |m|
      unless monedas_usadas.include?(m.id)
        detalles.build(moneda: m, forma: :efectivo, monto: 0, cotizacion: m.cotizacion)
      end
    end
        detalles.build(moneda: Moneda.first, forma: :tarjeta, monto: 0, cotizacion: 1)

  end

  # calcula si se va a producir saldo negativo para algunas monedas en la caja efectivo
  def check_detalles_negativos(deleted = false)

    monedas = detalles.map(&:moneda_id) # monedas de los detalles
    caja = Caja.get_caja_por_forma(:efectivo) # caja efectivo
    saldos = caja.saldos_por_moneda(monedas) # saldos de esas monedas

    if deleted
      detalles.each do |d|
        saldos[d.moneda_id] -= (d.monto)
      end
    else
      detalles.each do |d|
        saldos[d.moneda_id] += (d.monto - d.monto_was.to_f)
      end
    end
    monedas_negativas = saldos.map{ |m, v| m if v < 0 }.compact
    monedas_negativas.empty? ? [] : Moneda.find(monedas_negativas) # retorna un conjunto de monedas que pueden quedar con saldo negativo
  end

  # Agregar las monedas que no estan presentes
  # esto es para cuando se edita o hay un error al tratar de guardar
  def rebuild_detalles
    build_detalles(detalles.map(&:moneda_id))
  end

end

app/controllers/cobros_controller.rb
class CobrosController < ApplicationController
  layout 'imprimir', only: [:imprimir, :imprimir_show]

  before_action :set_cobro, only: [:show, :imprimir_show, :edit, :update, :destroy]

  before_action :setup_menu, only: [:index, :new, :edit, :show, :create, :update]

  # configuracion del menu
  def setup_menu
    @menu_setup[:main_menu] = :ventas
    @menu_setup[:side_menu] = :cobros_sidemenu
  end

  # busca las ventas y devoluciones pendientes de un cliente dado
  def buscar_pendientes
    @cliente = Cliente.find(params[:cliente_id])
    @ventas = @cliente.ventas_pendientes
    @devoluciones = @cliente.devoluciones_disponibles
  end

  def imprimir
    get_cobros
  end

  def imprimir_show
  end

  # GET /cobros
  # GET /cobros.json
  def index
    get_cobros
  end

  # GET /pagos/1
  # GET /pagos/1.json
  def show
  end

  # GET /cobros/new
  def new
    @cobro = Cobro.new
    @cobro.build_detalles
    render :form
  end

  # GET /cobros/1/edit
  def edit
    @cobro.rebuild_detalles
    render :form
  end

  # POST /cobros
  # POST /cobros.json
  def create
    @cobro = Cobro.new(cobro_params)
    @saldo_negativo = params[:guardar_si_o_si].present? ? [] : @cobro.check_detalles_negativos

    respond_to do |format|
      Cobro.transaction do
        if @saldo_negativo.size == 0 && @cobro.save
          format.html { redirect_to @cobro, notice: t('mensajes.save_success', recurso: 'el cobro') }
          format.json { render :show, status: :created, location: @cobro }
        else
          @cobro.rebuild_detalles
          format.html { render :form }
          format.json { render json: @cobro.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /cobros/1
  # PATCH/PUT /cobros/1.json
  def update
    @cobro.assign_attributes(cobro_params)
    @saldo_negativo = params[:guardar_si_o_si].present? ? [] : @cobro.check_detalles_negativos

    respond_to do |format|
      Cobro.transaction do
        if @saldo_negativo.size == 0 && @cobro.save
          format.html { redirect_to @cobro, notice: t('mensajes.update_success', recurso: 'el cobro') }
          format.json { render :show, status: :ok, location: @cobro }
        else
          @cobro.rebuild_detalles
          format.html { render :form }
          format.json { render json: @cobro.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /cobros/1
  # DELETE /cobros/1.json
  def destroy
    @cobro.destroy
    respond_to do |format|
      format.html { redirect_to cobros_url, notice: t('mensajes.delete_success', recurso: 'el cobro') }
      format.json { head :no_content }
    end
  end

  private
    def get_cobros
      procesar_fechas
      @search = Cobro.search(params[:q])
      @cobros = @search.result.includes(:persona).page(params[:page]).per(action_name == 'imprimir' ? LIMITE_REGISTROS_IMPRIMIR : 25)
    end

    # Setear las fechas "hasta" para que incluya el dia entero
    # 01/03/2016 => 2016-03-01 23:59:59
    def procesar_fechas
      if params[:q].present? && params[:q][:fecha_lt].present?
        params[:q][:fecha_lt] = params[:q][:fecha_lt].to_datetime.end_of_day
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_cobro
      @cobro = Cobro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cobro_params

      procesar_cantidades

      # se eliminan de params las boletas que no se seleccionaron o se marcan para eliminar
      params[:cobro][:boletas_detalles_attributes].each do |k, valor|
        if valor[:id].present?
          params[:cobro][:boletas_detalles_attributes][k][:_destroy] = '1' unless valor[:pagado].present?
        else
          params[:cobro][:boletas_detalles_attributes].delete(k) unless valor[:pagado].present?
        end
        end

      # se eliminan los creditos que no se seleccionaron para utilizar
      unless params[:cobro][:recibos_creditos_detalles_attributes].blank?
        params[:cobro][:recibos_creditos_detalles_attributes].each do |k, valor|
          if valor[:id].present?
            params[:cobro][:recibos_creditos_detalles_attributes][k][:_destroy] = '1' unless valor[:usado].present?
          else
            params[:cobro][:recibos_creditos_detalles_attributes].delete(k) unless valor[:usado].present?
          end
        end
      end

      params.require(:cobro).permit(:persona_id, :numero_comprobante, :fecha,
                                   detalles_attributes: [:id, :monto, :cotizacion, :moneda_id, :forma, :_destroy],
                                   boletas_detalles_attributes: [:id, :monto_utilizado, :boleta_id, :_destroy],
                                   recibos_creditos_detalles_attributes: [:id, :notas_creditos_debito_id, :monto_utilizado, :_destroy],
                                   )
    end

    def procesar_cantidades
      params[:cobro][:detalles_attributes].each do |i, d|
        params[:cobro][:detalles_attributes][i][:_destroy] = '1' if cantidad_a_numero(d[:monto]) == 0 # marcar para eliminar si el monto es cero
        params[:cobro][:detalles_attributes][i][:monto] = cantidad_a_numero(d[:monto])
        params[:cobro][:detalles_attributes][i][:cotizacion] = cantidad_a_numero(d[:cotizacion])
      end
    end

end

app/views/cobros/_credito_devoluciones.html.slim
- devoluciones.each_with_index do |d, i|
  - es_devolucion = d.instance_of?(DevolucionVenta)
  - devolucion = es_devolucion ? d : d.notas_creditos_debito
  - credito_restante = devolucion.credito_restante
  - if !cobro.nil? && cobro.persisted? && !es_devolucion # Sumar el monto utilizado al editar el cobro
    - credito_restante += d.monto_utilizado
  tr
    td = devolucion.id
    td = localize(devolucion.fecha.to_date)
    td.text-right = number_to_currency(devolucion.importe_total)
    td.text-right = number_to_currency(credito_restante)
    td
      div class="form-group #{'has-error' if d.errors.has_key?(:monto_utilizado)}"
        = hidden_field "cobro[recibos_creditos_detalles_attributes][#{i}]", :notas_creditos_debito_id, value: devolucion.id
        = text_field "cobro[recibos_creditos_detalles_attributes][#{i}]", :monto_utilizado, value: number_with_precision(es_devolucion ? devolucion.credito_restante : d.monto_utilizado), class: 'form-control mascaraMoneda monto-a-sumar'
        - if d.errors.has_key?(:monto_utilizado)
          span.help-block = d.errors.get(:monto_utilizado).to_sentence
    td
      - seleccionado = actualizando && !es_devolucion ? {checked: ''} : {} # checkear el cobro al editar o cuando hay errores en el create
      input type="checkbox" name="cobro[recibos_creditos_detalles_attributes][#{i}][usado]" class="usar-credito" *seleccionado
      - if !cobro.nil? && cobro.persisted? && !es_devolucion # incluir el id del detalle al editar
        input type="hidden" name="cobro[recibos_creditos_detalles_attributes][#{i}][id]" value="#{d.id}"

app/views/cobros/_list.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Fecha
      th Número de cobro
      th Nro. de comprobante
      th Cliente
      th Monto
  tbody
    - cobros.each do |cobro|
      tr.fila-clickeable data-url="#{cobro_path(cobro)}"
        td = localize(cobro.fecha.to_date)
        td = cobro.numero
        td.wordbreak = cobro.numero_comprobante
        td = cobro.persona_nombre
        td.text-right = number_to_currency(cobro.total_pagado + cobro.total_credito_utilizado)

app/views/cobros/form.html.slim
section.content-header
  h1 Ventas
section.content
  .row
    .col-xs-12
      .box
        = simple_form_for @cobro, html: { id: 'cobro-form' } do |f|
          .box-header
            a.volver-link href= cobros_path
              i.fa.fa-angle-double-left
              | Volver al listado de cobros
            .clearfix
            h3.box-title = @cobro.new_record? ? 'Nuevo Cobro' : "Editar Cobro Nro. #{@cobro.numero}"
          .box-body
            = f.error_notification
            .row
              .col-sm-9
                .row
                  .col-sm-4
                    = f.input :fecha, wrapper: :vertical_input_group do
                      = f.input_field :fecha, as: :string, class: 'datepicker form-control', autofocus: f.object.fecha.nil?, value: @cobro.new_record? && f.object.fecha.nil? ? '' : localize(f.object.fecha.to_date)
                      .input-group-btn
                        .btn.btn-default
                          i.fa.fa-calendar
                  .col-sm-4
                    = f.association :persona, as: :string, label: 'Cliente', disabled: @cobro.persisted?, input_html: { id: 'personas-buscador', placeholder: 'Buscar cliente...', data: { 'msg-required' => 'Este campo es obligatorio.',persona: f.object.persona.to_json } }
                .row
                  .col-sm-4
                    = f.input :numero_comprobante, label: 'Número de Comprobante'
            .row.overlay-wrapper#cobro-mensajes
              .overlay.hide
                i.fa.fa-refresh.fa-spin
              .col-xs-12
                .well.seleccionar-panel.text-center
                  i.fa.fa-search
                  h3 Seleccione un cliente para ver las boletas y devoluciones pendientes
            .row#pago-boletas-devoluciones.hide
              .col-xs-12#credito-devoluciones
                .form-subtitle
                  label Crédito de devoluciones
                br
                table.table.table-bordered.detalles-table#creditos-disponibles-tabla
                  thead
                    tr
                      th Número
                      th Fecha
                      th Monto
                      th Crédito disponible
                      th Crédito a usar
                      th
                  tbody#creditos-detalles-body
                    // Al editar Incluir devoluciones disponibles del proveedor que no sean las que ya estan asociadas al pago
                    - creditos_usados = @cobro.recibos_creditos_detalles.map(&:notas_creditos_debito_id)
                    - creditos_disponibles = @cobro.persona ? @cobro.persona.devoluciones_disponibles.reject { |d| creditos_usados.include?(d.id) } : []
                    = render 'credito_devoluciones', devoluciones: @cobro.recibos_creditos_detalles.to_a + creditos_disponibles.to_a, actualizando: true, cobro: @cobro
                  tfoot
                    tr
                      td colspan="3"
                      td.text-right.text-bold
                        | Total:
                      td.table-total.text-right.text-bold
                        span 0
                      td
              .col-xs-12
                .form-subtitle
                  label Boletas pendientes
                br
                p.text-danger.hide#boletas-seleccionadas-validation Debe seleccionar al menos una venta a cobrar
                table.table.table-bordered.detalles-table#venta-detalles-tabla
                  thead
                    tr
                      th Número
                      th Fecha
                      th Fecha de vencimiento
                      th Total Pendiente
                      th Total a cobrar
                      th
                  tbody#venta-detalles-body
                    - boletas_usadas = @cobro.boletas_detalles.map(&:boleta_id)
                    - boletas_disponibles = @cobro.persona ? @cobro.persona.ventas_pendientes.reject { |d| boletas_usadas.include?(d.id) } : []
                    = render 'ventas_pendientes', ventas: @cobro.boletas_detalles.to_a + boletas_disponibles.to_a, actualizando: true, cobro: @cobro
                  tfoot
                    tr
                      td colspan="3"
                      td.text-right.text-bold
                        | Total:
                      td.table-total.text-right.text-bold
                        span 0
                      td
              .col-xs-12
                .clearfix
                /////////////
                  RESUMEN DE TOTALES
                /////////////
                br
                .row#boleta-resumen
                  .col-sm-offset-8.col-sm-4
                    table.table.bg-warning
                      tbody
                        tr
                          td Total boletas:
                          td.text-right#res-total-boleta data-total="0" Gs. 0
                        tr
                          td Crédito utilizado:
                          td.text-right#res-total-creditos data-total="0" Gs. 0
                        tr
                          td.text-bold Total a cobrar:
                          td.text-right.text-bold#res-total-a-cobrar Gs. 0

            .row#cobro-detalles.hide
              .col-xs-12
                .form-subtitle
                  label Formas de cobro
                br
                - esconder_validacion_detalles = @cobro.errors.has_key?(:importe_total) ? '' : 'hide'
                p#recibo-total-validation class="text-danger #{esconder_validacion_detalles}" El total de las formas de cobro debe ser igual al total a cobrar de las boletas seleccionadas.

                table.table.table-bordered.detalles-table.calcular-cobros-total
                  thead
                    tr
                      th Forma
                      th Moneda
                      th Monto
                      th Cotización
                      th Subtotal
                      th
                  tbody#cobro-detalles-body
                    = f.simple_fields_for :detalles do |detalle|
                      = render 'detalles', f: detalle
                  tfoot
                    tr
                      td colspan="3"
                      td.text-right.text-bold
                        | Total:
                      td.table-total.text-right.text-bold
                        span
                      td
          .box-footer
            - if @saldo_negativo && @saldo_negativo.size > 0
              input.hidden name="guardar_si_o_si" value= "true"
              .alert.alert-warning#mensaje-saldo-negativo
                p
                  | La operación va a provocar que los fondos de la caja quede en negativo para las siguientes monedas: #{@saldo_negativo.map(&:nombre).to_sentence}.
                p Esta seguro que quiere continuar?
                .form-actions
                  = link_to 'Cancelar', cobros_path, class: 'btn btn-default'
                  | #{' '}
                  button.btn.btn-primary type="submit" Continuar
            - else
              .form-actions.text-right
                = link_to 'Cancelar', cobros_path, class: 'btn btn-default'
                | #{' '}
                button.btn.btn-primary type="submit" Guardar Cobro


javascript:
  CobrosUI.setbuscarClienteUrl("#{clientes_buscar_path}");
  CobrosUI.setboletasPendientesUrl("#{cobros_buscar_pendientes_path}");

- if @saldo_negativo && @saldo_negativo.size > 0
  javascript:
    MensajesHelper.irHasta($('#mensaje-saldo-negativo').offset().top);

app/views/cobros/imprimir.html.slim
h4 Listado de cobros
= render 'list', cobros: @cobros

app/views/cobros/imprimir_show.html.slim
= render template: "cobros/show"

app/views/cobros/index.html.slim
section.content-header
  h1 Ventas
section.content
  .row
    .col-xs-12
      .box
        .box-header
          h3.box-title Listado de cobros
          .box-tools.pull-right.hidden-print
            = link_to '<i class="fa fa-print"></i> Imprimir'.html_safe, cobros_imprimir_url, class: 'btn btn-default imprimir-listado'
            = ' '
            = link_to 'Nuevo cobro', new_cobro_path, class: 'btn btn-primary'
        .box-body#boletas-lista
          #venta-search.buscador-listado.hidden-print
            = search_form_for @search, remote: true, class: 'remote-search' do |f|
              .row
                .col-xs-3
                  div#date-range.btn.btn-default.daterange.btn-block
                    = f.hidden_field :fecha_gteq , class: 'fecha-desde'
                    = f.hidden_field :fecha_lteq , class: 'fecha-hasta'
                    i.fa.fa-calendar
                    span Fecha
                    b.caret
                .col-xs-4
                  .input-group
                    = f.search_field :numero_comprobante_or_id_cont, class: 'form-control', placeholder: 'Nro. de cobro o de comprobante...'
                    .input-group-btn
                      button.btn.btn-default type="submit" name="commit"
                        i.fa.fa-search
                .col-xs-4
                  .form-group
                    = f.search_field :persona_id_eq_any, id: 'personas-buscador', class: 'form-control', placeholder: 'Todos los clientes...'
          #cobros-table.overlay-wrapper.buscador-resultados.table-responsive
            = render 'list', cobros: @cobros
          #cobros-paginate-container.hidden-print
            = paginate @cobros, remote: true
javascript:
  CobrosUI.setbuscarClienteUrl("#{clientes_buscar_path}");

app/views/cobros/show.html.slim
section.content-header
  h1 Ventas
section.content
  .row
    .col-xs-12
      .box
        .box-header
          a.volver-link.hidden-print href="#{cobros_path}"
            i.fa.fa-angle-double-left
            | Volver al listado de cobros
          .clearfix
          h3.box-title Cobro Nro. #{@cobro.numero}
          .box-tools.hidden-print
            = link_to 'Imprimir'.html_safe, "/cobros/#{@cobro.id}/imprimir_show", class: 'btn btn-default imprimir-listado'
            = ' '
            - if @cobro.credito?
              = link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_cobro_path(@cobro), class: 'btn btn-default'
            - else
              button.btn.btn-default.disabled data-toggle="tooltip" title="No se puede editar el cobro porque pertenece a una venta al contado."
                i.fa.fa-edit
                |  Editar
            = ' '
            - if @cobro.credito?
              - if @stock_negativo && @stock_negativo.size > 0
                = link_to '<i class="fa fa-trash"></i> Eliminar'.html_safe, cobro_path(@cobro), method: 'delete', data: {confirm: "La operación va a provocar existencia negativa en los siguientes productos: #{@stock_negativo.map {|m| m.nombre }.to_sentence}. ¿Seguro que desea eliminar la cobro?"}, class: 'btn btn-danger'
              - else
                = link_to '<i class="fa fa-trash"></i> Eliminar'.html_safe, cobro_path(@cobro), method: 'delete', data: {confirm: "¿Desea eliminar el cobro?"}, class: 'btn btn-danger'
            - else
              button.btn.btn-danger.disabled data-toggle="tooltip" title="No se puede eliminar el cobro porque pertenece a una venta al contado."
                i.fa.fa-trash
                |  Eliminar
        .box-body
          .row
            .col-sm-9
              .row
                .col-sm-4
                  label.control-label Fecha
                  p = localize(@cobro.fecha.to_date)
                .col-sm-4
                  label.control-label Cliente
                  p = @cobro.persona_nombre
              .row
                .col-sm-4
                  label.control-label Nro. de Comprobante
                  p = @cobro.numero_comprobante
  .row
    .col-xs-12
      .nav-tabs-custom
        ul.nav.nav-tabs.hidden-print
          li.active
            a href="#detalles" data-toggle="tab" Formas de cobro
          li
            a href="#ventas" data-toggle="tab" Ventas Cobradas
          li
            a href="#creditos" data-toggle="tab" Crédito utilizado
        .tab-content
          .tab-pane.active#detalles
            h4.visible-print Formas de Cobro
            table.table.table-bordered.detalles-table.calcular-total
              thead
                tr
                  th Forma
                  th Moneda
                  th Monto
                  th Cotización
                  th Subtotal
              tbody#movimiento-detalles-body
                - total = 0
                - @cobro.detalles.each do |d|
                  tr
                    td = d.forma_text
                    td = d.moneda_nombre
                    td.text-right = number_to_currency(d.monto, unit: '')
                    td.text-right = number_to_currency(d.cotizacion, unit: '')
                    td.text-right = number_to_currency(d.monto * d.cotizacion, unit: '')
                  - total += d.monto * d.cotizacion
              tfoot
                tr
                  td colspan="3"
                  td.text-right.text-bold
                    | Total:
                  td.table-total.text-right.text-bold
                    span = number_to_currency(total)
          .tab-pane#ventas
            h4.visible-print Ventas Cobradas
            table.table.table-bordered.detalles-table.calcular-cobros-total
              thead
                tr
                  th Número
                  th Nro. de comprobante
                  th Fecha
                  th Importe total
                  th Importe cobrado
              tbody
                - total_ventas = 0
                - @cobro.boletas_detalles.each do |bd|
                  - venta = bd.boleta
                  - total_ventas += bd.monto_utilizado
                  tr.fila-clickeable data-url="#{venta_path(venta.id)}"
                    td = venta.numero
                    td = venta.numero_comprobante
                    td = localize(venta.fecha.to_date)
                    td.text-right = number_to_currency(venta.importe_total, unit: '')
                    td.text-right = number_to_currency(bd.monto_utilizado, unit: '')
              tfoot
                tr
                  td colspan="3"
                  td.text-right.text-bold
                    | Total:
                  td.table-total.text-right.text-bold
                    span = number_to_currency(total_ventas)
          .tab-pane#creditos
            h4.visible-print Crédito Utilizado
            table.table.table-bordered.detalles-table
              thead
                tr
                  th Fecha
                  th Número
                  th Monto
                  th Monto usado
              tbody#movimiento-detalles-body
                - total = 0
                - @cobro.recibos_creditos_detalles.each do |p|
                  - total += p.monto_utilizado
                  tr.fila-clickeable data-url="#{devolucion_venta_path(p.notas_creditos_debito.id)}"
                    td = localize(p.notas_creditos_debito.fecha.to_date)
                    td = p.notas_creditos_debito.id
                    td.text-right = number_to_currency(p.notas_creditos_debito.importe_total)
                    td.text-right = number_to_currency(p.monto_utilizado)
              tfoot
                tr
                  td
                  td
                  td.text-right.text-bold
                    | Total:
                  td.table-total.text-right.text-bold
                    span = number_to_currency(total)
  - if @cobro.total_credito_utilizado > 0
    .row
      .col-sm-offset-8.col-sm-4
        .box.box-solid
          .box-body
            h4.visible-print Resumen
            table.table.bg-warning
              tbody
                tr
                  td Total boletas:
                  td.text-right = "#{number_to_currency(@cobro.total_pagado + @cobro.total_credito_utilizado)}"
                - if @cobro.total_credito_utilizado > 0
                  tr
                    td Crédito utilizado:
                    td.text-right = "#{number_to_currency(@cobro.total_credito_utilizado)}"
                tr
                  td.text-bold Total formas de cobro:
                  td.text-right.text-bold = number_to_currency(@cobro.total_pagado)