config/routes.rb
Rails.application.routes.draw do

  get 'devolucion_compras/get_compras' => 'devolucion_compras#get_compras'
  get 'devolucion_compras/buscar_compra' => 'devolucion_compras#buscar_compra'
  get 'devolucion_compras/imprimir' => 'devolucion_compras#imprimir'
  get 'devolucion_compras/:id/imprimir_show' => 'devolucion_compras#imprimir_show'
  resources :devolucion_compras

  get 'devolucion_ventas/get_ventas' => 'devolucion_ventas#get_ventas'
  get 'devolucion_ventas/buscar_venta' => 'devolucion_ventas#buscar_venta'
  get 'devolucion_ventas/imprimir' => 'devolucion_ventas#imprimir'
  get 'devolucion_ventas/:id/imprimir_show' => 'devolucion_ventas#imprimir_show'
  resources :devolucion_ventas

  devise_for :users

  get 'configuraciones/check_empresa_nombre' => 'configuraciones#check_empresa_nombre'
  resources :configuraciones, only: [:index, :edit, :update]

  get 'proveedores/check_nombre' => 'proveedores#check_nombre'
  get 'proveedores/buscar' => 'proveedores#buscar'
  resources :proveedores

  get 'clientes/check_nombre' => 'clientes#check_nombre'
  get 'clientes/buscar' => 'clientes#buscar'
  resources :clientes

  get 'cuentas_corrientes/clientes'
  get 'cuentas_corrientes/proveedores'
  get 'cuentas_corrientes/imprimir_extracto'

  get 'empleados/check_nombre' => 'empleados#check_nombre'
  resources :empleados

  get 'categorias/check_nombre' => 'categorias#check_nombre'
  resources :categorias

  get 'mercaderias/check_codigo' => 'mercaderias#check_codigo'
  get 'mercaderias/buscar' => 'mercaderias#buscar'
  get 'mercaderias/historico' => 'mercaderias#historico'
  get 'mercaderias/imprimir_historico' => 'mercaderias#imprimir_historico'
  resources :mercaderias, except: [:show]

  resources :inventarios, only: [:index]

  resources :movimiento_mercaderias

  get 'monedas/check_nombre' => 'monedas#check_nombre'
  resources :monedas

  get 'categoria_gastos/check_nombre' => 'categoria_gastos#check_nombre'
  resources :categoria_gastos

  get 'compras/buscar_devoluciones' => 'compras#buscar_devoluciones'
  get 'compras/imprimir' => 'compras#imprimir'
  get 'compras/:id/imprimir_show' => 'compras#imprimir_show'
  resources :compras

  get 'ventas/buscar_devoluciones' => 'ventas#buscar_devoluciones'
  get 'ventas/imprimir' => 'ventas#imprimir'
  get 'ventas/:id/imprimir_show' => 'ventas#imprimir_show'
  resources :ventas

  get 'pagos/buscar_pendientes' => 'pagos#buscar_pendientes'
  get 'pagos/imprimir' => 'pagos#imprimir'
  get 'pagos/:id/imprimir_show' => 'pagos#imprimir_show'
  resources :pagos

  get 'caja_movimientos/new_transferencia' => 'caja_movimientos#new_transferencia'
  post 'caja_movimientos/create_transferencia' => 'caja_movimientos#create_transferencia'
  get 'caja_movimientos/imprimir' => 'caja_movimientos#imprimir'
  get 'caja_movimientos/:id/imprimir_show' => 'caja_movimientos#imprimir_show'

  resources :caja_movimientos, except: [:edit, :update, :destroy]

  get 'cobros/buscar_pendientes' => 'cobros#buscar_pendientes'
  get 'cobros/imprimir' => 'cobros#imprimir'
  get 'cobros/:id/imprimir_show' => 'cobros#imprimir_show'
  resources :cobros

  get 'reportes/compras'
  get 'reportes/imprimir_reporte_compras'
  get 'reportes/ventas'
  get 'reportes/imprimir_reporte_ventas'
  get 'reportes/gastos'
  get 'reportes/imprimir_reporte_gastos'
  get 'reportes/caja'
  get 'reportes/imprimir_reporte_caja'

  get 'welcome/index'
  get 'welcome/devoluciones_venta'
  get 'welcome/devoluciones_compra'
  get 'welcome/devoluciones_venta_index'
  get 'welcome/devoluciones_compra_index'

  root 'welcome#index'

end

app/models/empleado.rb
class Empleado < Persona
  accepts_nested_attributes_for :user
  validates_presence_of :user
  validates :nombre, presence: true
  validates :nombre, length: {maximum: 150, minimum: 2}
  validates :nombre, uniqueness: true
  validates :numero_documento, format: { with: /\A(\d+[.]*[ ]*-?)+\z/, message: :only_numbers_is_allowed }, allow_blank: false
  delegate :username, :rol, :id, to: :user, prefix: true
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]
  before_action :setup_menu, only: [:index]

  # configuracion del menu
  def setup_menu
    @menu_setup[:main_menu] = :configuraciones
    @menu_setup[:side_menu] = :empleados_sidemenu
  end

  # GET /empleados
  # GET /empleados.json
  def index
    get_empleados
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
    @user = @empleado.build_user
    render 'load_form', format: :js
  end

  # GET /empleados/1/edit
  def edit
    render 'load_form', format: :js
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)
    if @empleado.save
      @error = false
      @message = "Se ha guardado el usuario"
      get_empleados
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de guardar el usuario. #{@empleado.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    if params[:empleado][:user_attributes][:password].blank? && params[:empleado][:user_attributes][:password_confirmation].blank?
      params[:empleado][:user_attributes].delete(:password)
      params[:empleado][:user_attributes].delete(:password_confirmation)
    end
    @empleado.assign_attributes(empleado_params)
    @redirect = true if @empleado.user.encrypted_password_changed? && @empleado.user.id == current_user.id
    if @empleado.save
      @error = false
      @message = "Se ha guardado el usuario"
      get_empleados
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de guardar el usuario. #{@empleado.errors.full_messages.to_sentence}"
    end

    render 'reload_list', format: :js
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    if @empleado.destroy
      @error = false
      @message = "Se ha eliminado el usuario"
      get_empleados
    else
      @error = true
      @message = "Ha ocurrido un problema al tratar de eliminar el usuario"
    end

    render 'reload_list', format: :js
  end

  # Comprobar si ya existe el empleado con el nombre dado
  def check_nombre
    empleado = Empleado.by_nombre(params[:nombre]).first

    render json: (empleado.nil? || empleado.id == params[:id].to_i) ? true : t('empleado.unique_nombre_error', nombre: params[:nombre]).to_json
  end

  def get_empleados
    @search = Empleado.search(params[:q])
    @empleados = @search.result.includes(:user).page(params[:page])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
      @user = @empleado.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :telefono, :direccion, :numero_documento, { user_attributes: [ :id, :username, :password, :password_confirmation, :rol] })
    end
end

app/views/empleados/_form.html.slim
= simple_form_for empleado, url: !empleado.new_record? ? empleado_path(empleado) : empleados_path,
                              html: {id: 'empleado-form'},
                              remote: true do |f|
  .modal-header
    button.close type="button" data-dismiss="modal"
      span &times;
    h4.modal-title
      = empleado.new_record? ? 'Nuevo Usuario' : 'Editar Usuario'
  .modal-body
    = f.input :id, as: :hidden, input_html: { id: 'empleado_id' }
    = f.input :nombre, autofocus: true,    input_html: {class: 'uniqueEmpleadoNombre'}
    = f.simple_fields_for :user do |u|
      = u.input :username
      = u.input :password
      = u.input :password_confirmation, label: 'Repetir contraseña', input_html: {class: 'passwordConfirmation'},  maxlength: 20, size: 20
      - if current_user.id != empleado.user.id
          = u.input :rol, include_blank: false, disabled: false
      - else
        = u.input :rol, include_blank: false, disabled: true
    = f.input :direccion
    = f.input :telefono
    = f.input :numero_documento, label: 'Nro. de documento'
  .modal-footer.text-right
    button.btn.btn-default.pull-left [type="button" data-dismiss="modal" aria-hidden="true"] Cancelar
    input.btn.btn-primary type="submit" value="Guardar" data-disable-with="Guardando..."

javascript:
  EmpleadosUI.initFormEvents("#{empleados_check_nombre_path}");

app/views/empleados/_list.html.slim
table.table.table-bordered.table-hover
  thead
    tr
      th Nombre
      th Nombre de usuario
      th Nro. de Documento
      th Rol
      th Teléfono
      th Dirección
      th.table-actions
  tbody
    - empleados.each do |empleado|
      tr
        td = cortar_texto(empleado.nombre)
        td = empleado.user_username
        td = empleado.numero_documento
        td = empleado.user_rol
        td = empleado.telefono
        td = cortar_texto(empleado.direccion)
        td
          - unless empleado.user.superusuario? && !current_user.superusuario?
            = link_to '<i class="fa fa-edit"></i> '.html_safe, edit_empleado_path(empleado), remote: true, class: 'btn btn-default btn-sm'
          - unless empleado.user.id == current_user.id || empleado.user.superusuario?
              = link_to ' <i class="fa fa-trash"></i>'.html_safe, empleado_path(empleado), method: 'delete', data: {confirm: "¿Desea eliminar el usuario #{empleado.user_username}?"}, remote: true, class: 'btn btn-danger btn-sm'

app/views/empleados/index.html.slim
section.content-header
  h1 Usuarios
section.content
  .row
    .col-xs-12
      .box
        .box-header
          h3.box-title Listado de Usuarios
          .box-tools.pull-right
            = link_to 'Nuevo Usuario', new_empleado_path, class: 'btn btn-primary', remote: true
        .box-body#users-lista
          #empleado-search.buscador-listado
            = search_form_for @search, remote: true, class: 'remote-search' do |f|
              .input-group
                = f.text_field :nombre_or_numero_documento_or_user_username_cont, class: 'form-control', placeholder: 'Buscar por nombre o nombre de usuario o número de documento...', autofocus: true
                .input-group-btn
                  button.btn.btn-default type="submit" name="commit"
                    i.fa.fa-search
          #empleados-table.overlay-wrapper.buscador-resultados.table-responsive
            = render partial: 'empleados/list', locals: {empleados: @empleados}
          #paginate-container
            = paginate @empleados, remote: true

app/views/empleados/index.js.slim
| $("#empleados-table").html("#{escape_javascript(render partial: 'list', format: 'html', locals: {empleados: @empleados})}");
| $('#paginate-container').html("#{escape_javascript(paginate(@empleados, remote: true)) }");
| $('.buscador-resultados > .overlay').remove();

app/views/empleados/load_form.js.slim
| var modal = $('#main-modal');
| modal.find('.modal-content').html("#{escape_javascript(render partial: 'form', format: :html, locals: {empleado: @empleado, user: @user})}");
| modal.modal('show');

app/views/empleados/reload_form.js.slim
| var modal = $('#main-modal');
- if @error
  | noty({type: "error", text : "#{@message}"});
- else
  | noty({type: "success", text : "#{@message}"});
  | modal.modal('hide');
  | $('#user-lista').html("#{escape_javascript(render partial: 'list', locals: {persona: @persona, user: @user})}");

app/views/empleados/reload_list.js.slim
- if @redirect
  | window.location = "#{root_path}";
| var modal = $('#main-modal');
- if @error
  | noty({type: "error", text : "#{@message}"});
- else
  | noty({type: "success", text : "#{@message}"});
  | modal.modal('hide');
  | $('#empleados-table').html("#{escape_javascript(render 'list', empleados: @empleados)}");
  | $('#paginate-container').html("#{escape_javascript(paginate(@empleados, params: {controller: :empleados, action: :index}, remote: true)) }");

app/views/empleados/show.html.slim
p#notice = notice

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', user_path